export const GET_LATEST_RATES = "GET_LATEST_RATES";
export const GET_RATES_BY_BASE = "GET_RATES_BY_BASE";
export const GET_RATES_FOR_SYMBOLS = "GET_RATES_FOR_SYMBOLS";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const GET_QUERY_RESULT = "GET_LATEST_QUERY";
export const CONVERT_CURRENCY = "CONVERT_CURRENCY";
export const GET_ALL_CODES = "GET_ALL_CODES"
